#!/usr/bin/env python3

#
# This file is part of ChromatiX.
#
# Copyright (c) 2026 Florent Kermarrec <florent@enjoy-digital.fr>
# SPDX-License-Identifier: GPL-3.0-only
# Derived from ModRetro's oss-chromatic-console-fpga (GPL-3.0).

"""
ChromatiX: LiteX based FPGA design for the ModRetro Chromatic handheld.

Integrates clock generation, button debouncing, LCD/video pipeline, audio I2S, I2C codec control,
memory system, Game Boy emulation core, USB UVC+UART, battery ADC and system monitoring.
"""

import os
import argparse
import subprocess
from types import MethodType, SimpleNamespace

from migen import *

from litex.gen import *
from litex.gen.genlib.cdc import BusSynchronizer

from litex.soc.interconnect import stream
from litex.soc.interconnect import wishbone

from litex.soc.cores.uart           import UARTBone
from litex.soc.integration.soc      import SoCRegion, MB
from litex.soc.integration.soc_core import SoCMini
from litex.soc.integration.builder  import Builder

from chromatix import Platform

from chromatix.gateware.crg        import CRG
from chromatix.gateware.sources    import add_verilog_sources
from chromatix.gateware.usb_device import USBDevice
from chromatix.gateware.misc       import TickGenerator, StatusLed, ESP32Control
from chromatix.gateware.buttons    import Buttons, BUTTONS
from chromatix.gateware.debug      import DebugControl
from chromatix.gateware.memory     import MemorySystem
from chromatix.gateware.vcart      import VirtualCart, VirtualCartCSR
from chromatix.gateware.demo       import ButtonsCSR, ToneGenerator, PCMAudio
from chromatix.gateware.video      import VideoPipeline
from chromatix.gateware.lcd        import ST7785Init, load_st7785_sequence
from chromatix.gateware.codec      import CodecControl, CodecI2S, load_tlv320_registers
from chromatix.gateware.sysmon     import SystemMonitorUART, SystemMonitorBridge, SystemMonitorPayloads, SystemMonitorControl
from chromatix.gateware.adc        import BatteryADC
from chromatix.gateware.terminal   import LCDTerminal
from chromatix.gateware.framebuffer import LCDFramebuffer

# Timing Constraints -------------------------------------------------------------------------------

TIMING_CONSTRAINTS = [
    # Generated PLL clocks (main PLL, managed by LiteX).
    'create_generated_clock -name xclk2 -source [get_ports {clk_fpga}] -master_clock clk_fpga -divide_by 1 -multiply_by 4 [get_pins {PLLA/CLKOUT0}]',
    'create_generated_clock -name pclk  -source [get_ports {clk_fpga}] -master_clock clk_fpga -divide_by 1 -multiply_by 1 [get_pins {PLLA/CLKOUT1}]',
    'create_generated_clock -name hclk  -source [get_ports {clk_fpga}] -master_clock clk_fpga -divide_by 2 -multiply_by 1 [get_pins {PLLA/CLKOUT2}]',
    'create_generated_clock -name gclk  -source [get_ports {clk_fpga}] -master_clock clk_fpga -divide_by 4 -multiply_by 1 [get_pins {PLLA/CLKOUT3}]',
    'create_generated_clock -name xclk  -source [get_ports {clk_fpga}] -master_clock clk_fpga -divide_by 1 -multiply_by 2 [get_pins {PLLA/CLKOUT4}]',
    # QSPI clock.
    'create_clock -name sclk -period 25 [get_ports {qspi_clk}]',
    # Note: pclk/hclk/gclk/xclk are generated by the same PLL with integer ratios: keep the paths
    # between them timed (the Game Boy core has synchronous pclk <-> hclk paths).
    # Cartridge bus timing constraints.
    'set_max_delay -from [get_ports {cart_d[*]}] -to [get_clocks {hclk}] 13',
    'set_max_delay -from [get_clocks {hclk}] -to  [get_ports {cart_a[*]}] 14',
    'set_max_delay -from [get_clocks {hclk}] -to  [get_ports {cart_wr}] 14',
    'set_max_delay -from [get_clocks {hclk}] -to  [get_ports {cart_rd}] 14',
    'set_max_delay -from [get_clocks {hclk}] -to  [get_ports {cart_cs}] 14',
    'set_max_delay -from [get_clocks {hclk}] -to  [get_ports {link_sd}] 14',
    'set_max_delay -from [get_clocks {hclk}] -to  [get_ports {cart_d[*]}] 14',
    # USB clocks (USB PLL and USB PHY SerDes clock divider, 120MHz).
    'create_generated_clock -name PHY_CLKOUT -source [get_ports {clk_24}] -master_clock clk_24 -divide_by 16 -multiply_by 40 [get_pins {usb_pll/CLKOUT1}]',
    'create_generated_clock -name fclk_960M  -source [get_ports {clk_24}] -master_clock clk_24 -divide_by 1  -multiply_by 40 [get_pins {usb_pll/CLKOUT0}]',
    'create_clock -name usbintsclk -period 8.333 [get_nets {{{usb_sclk}}}]',
    'set_clock_groups -asynchronous -group [get_clocks {PHY_CLKOUT}] -group [get_clocks {fclk_960M}]',
    'set_clock_groups -asynchronous -group [get_clocks {PHY_CLKOUT}] -group [get_clocks {usbintsclk}]',
    'set_clock_groups -asynchronous -group [get_clocks {fclk_960M}] -group [get_clocks {usbintsclk}]',
]

USB_SCLK_NET = "usb_hs_clk" # USB2PHY SerDes clock divider output (120MHz).

PSRAM_BASE = 0x40000000 # PSRAM on the SoC bus (debug bridge, Game Boy mode).

# Doom: CPU main RAM in the PSRAM (OSD/framebuffers/BIST below).
DOOM_RAM_OFFSET = 0x080000
DOOM_RAM_SIZE   = 8*MB - DOOM_RAM_OFFSET

def add_timing_constraints(platform):
    constraints = [c.replace("{{{usb_sclk}}}", "{" + USB_SCLK_NET + "}") for c in TIMING_CONSTRAINTS]
    original_build_timing_constraints = platform.toolchain.build_timing_constraints

    def build_timing_constraints(toolchain, vns):
        sdc = original_build_timing_constraints(vns)
        with open(sdc[0], "a", encoding="utf-8") as f:
            f.write("\n" + "\n".join(constraints) + "\n")
        return sdc

    platform.toolchain.build_timing_constraints = MethodType(build_timing_constraints, platform.toolchain)

# BaseSoC ------------------------------------------------------------------------------------------

class BaseSoC(SoCMini):
    """
    ChromatiX Top-Level.

    Integrates all subsystems of the ModRetro Chromatic handheld: clock generation, video/LCD
    pipeline, audio I2S with TLV320 codec, Game Boy emulation core, memory controller, USB
    UVC+UART, ESP32 MCU communication, battery ADC, button debouncing, and system monitoring.
    """
    def __init__(self, platform,
        with_debug_bridge     = False,
        debug_bridge_baudrate = 115200,
        uvc_frames            = None,
        with_bios             = False,
        with_doom             = False,
        with_utmi_monitor     = False):
        gclk_freq = int(33.55432e6 / 4)
        pclk_freq = int(33.55432e6)
        hclk_freq = int(33.55432e6 / 2)
        # LiteX "sys" domain: gClk, or pClk for the CPU (BIOS demo, Doom).
        with_cpu     = with_bios or with_doom
        sys_clk_freq = pclk_freq if with_cpu else gclk_freq
        assert not (with_bios and with_doom)
        assert not (with_cpu and with_debug_bridge) # Both use the USB CDC port.
        with_vcart = with_debug_bridge # Virtual cartridge loaded over the debug bridge.

        # SoCMini (CSR bus in the sys domain: gClk, or pClk for the BIOS demo) ---------------------

        # LiteX BIOS demo: VexRiscv + BIOS (integrated ROM/SRAM) in place of the Game Boy core,
        # console on the USB CDC port and on the LCD (so also on the UVC capture).
        cpu_kwargs = {}
        if with_bios:
            cpu_kwargs = dict(
                cpu_type             = "vexriscv",
                cpu_variant          = "lite",
                integrated_rom_size  = 0x6000,
                integrated_sram_size = 0x2000,
                with_timer           = True,
            )
        # Doom: VexRiscv with I/D caches, no ROM: firmware (and WAD) loaded in the PSRAM main RAM by
        # the host over UARTBone (CPU held in reset with ctrl cpu_rst), console on a crossover UART.
        if with_doom:
            cpu_kwargs = dict(
                cpu_type             = "vexriscv",
                cpu_variant          = "standard",
                cpu_reset_address    = 0x40000000,
                integrated_rom_size  = 0,
                integrated_sram_size = 0, # Stack/data in the main RAM (BSRAM for the framebuffer).
                with_timer           = True,
            )
        SoCMini.__init__(self, platform,
            clk_freq      = sys_clk_freq,
            ident         = "ChromatiX SoC" + {
                (True,  False): " (LiteX BIOS demo)",
                (False, True):  " (Doom)",
            }.get((with_bios, with_doom), ""),
            ident_version = True,
            **cpu_kwargs,
        )

        # CRG --------------------------------------------------------------------------------------

        self.crg = crg = CRG(platform, sys_clk="pclk" if with_cpu else "gclk")

        # Platform Resources -----------------------------------------------------------------------

        clk_24   = platform.request("clk_24")
        clk_27   = platform.request("clk_27")  # Unused but required by platform constraints.
        buttons  = platform.request("buttons")
        rgb_led  = platform.request("rgb_led")
        power    = platform.request("power")
        esp32    = platform.request("esp32_ctrl")
        serial   = platform.request("serial")
        esp_uart = platform.request("esp32_uart0")
        qspi     = platform.request("qspi")
        ps       = platform.request("ps")
        cart     = platform.request("cart")
        lcd      = platform.request("lcd")
        audio    = platform.request("audio_codec")
        i2s      = platform.request("i2s")
        ir       = platform.request("ir")
        link     = platform.request("link")
        i2c      = platform.request("i2c")
        usb      = platform.request("usb")
        hdmi     = platform.request("hdmi")
        vbat_adc = platform.request("vbat_adc")
        sdio_ls  = platform.request("sdio_ls")

        # SDIO level shifter enable.
        self.comb += sdio_ls.eq(1)

        # Inter-Module Signals ---------------------------------------------------------------------

        # Video.
        h_wr_burst_q      = Signal(16)
        h_wr_burst_q2     = Signal(16)
        gb_lcd_clkena     = Signal()
        gb_lcd_data       = Signal(15)
        gb_lcd_mode       = Signal(2)
        gb_lcd_on         = Signal()
        gb_lcd_vsync      = Signal()
        h_gb_newline      = Signal()
        h_gb_address      = Signal(23)
        h_gb_write        = Signal()
        h_gb_data         = Signal(16)
        h_draw_osd        = Signal()
        slide_out_active  = Signal()
        lcd_init_done     = Signal()
        lcd_enable_uvc    = Signal()
        lcd_db_uvc        = Signal(18)

        # Audio.
        left              = Signal(16)
        right             = Signal(16)

        # System.
        debug_system      = Signal(32)
        system_control    = Signal(16)
        low_battery       = Signal()
        boot_rom_enabled  = Signal()
        lcd_on_int        = Signal()
        lcd_off_overwrite = Signal()
        menu_disabled     = Signal()
        mcu_buttons       = Signal(9)
        q_menu_init       = Signal()

        # Palette.
        palette_bg_in     = Signal(64)
        palette_obj0_in   = Signal(64)
        palette_obj1_in   = Signal(64)
        gbc_mode          = Signal()
        gpd               = Signal(64)

        # Timers (gClk domain) ---------------------------------------------------------------------

        self.ticks = ticks = ClockDomainsRenamer("gclk")(TickGenerator())

        # Cart Detect Debounce & Memory Reset (xClk domain) ----------------------------------------

        cart_det_sr = Signal(18)
        memrst      = Signal(reset=1)

        # 18-bit shift register sampling cart detect pin.
        self.sync.xclk += cart_det_sr.eq(Cat(cart.det, cart_det_sr[:17]))

        # memrst: set when PLL unlocked, or on cart detect transitions.
        self.sync.xclk += [
            If(~crg.pll.locked,
                memrst.eq(1),
            ).Else(
                memrst.eq(
                    (cart_det_sr[2:18] == 0x7FFF) |
                    (cart_det_sr[2:18] == 0x8000)
                ),
            ),
        ]

        # Status LED (xClk domain) -----------------------------------------------------------------

        self.status_led = status_led = ClockDomainsRenamer("xclk")(StatusLed(rgb_led))
        self.comb += [
            status_led.reset.eq(~crg.pll.locked),
            status_led.blink.eq(ticks.counter[4]),
        ]

        # LCD Enable Sync (gClk domain) ------------------------------------------------------------

        lcd_vsync_r1       = Signal()
        lcd_en0            = Signal()
        lcd_en1            = Signal()
        lcd_en             = Signal()
        lcd_backlight_init = Signal()

        # Three-stage vsync-synchronized LCD enable with init gating.
        self.sync.gclk += [
            lcd_vsync_r1.eq(lcd.vsync),
            If(memrst,
                lcd_en.eq(0), lcd_en0.eq(0), lcd_en1.eq(0),
            ).Else(
                If(lcd.vsync & ~lcd_vsync_r1,
                    lcd_en0.eq(lcd_init_done & lcd_backlight_init),
                    lcd_en1.eq(lcd_en0),
                    lcd_en.eq(lcd_en1),
                ),
            ),
        ]

        # USB Init Delay (gClk domain) -------------------------------------------------------------

        usb_init_cnt = Signal(24, reset=0)
        usb_rst      = Signal(reset=1)

        # Hold USB in reset until ~1s after PLL lock.
        self.sync.gclk += [
            If(~crg.pll.locked,
                usb_init_cnt.eq(0),
                usb_rst.eq(1),
            ).Elif(usb_init_cnt < 8388607,
                usb_init_cnt.eq(usb_init_cnt + 1),
                usb_rst.eq(1),
            ).Else(
                usb_rst.eq(0),
            ),
        ]

        # UVC Pipeline Registers (gClk domain) -----------------------------------------------------

        hr1 = Signal()
        vr1 = Signal()
        he1 = Signal()
        d1  = Signal(18)

        # One-stage pipeline delay for UVC video path, cleared on memrst.
        self.sync.gclk += [
            If(memrst,
                hr1.eq(0), vr1.eq(0), he1.eq(0), d1.eq(0),
            ).Else(
                hr1.eq(lcd.hsync),
                vr1.eq(lcd.vsync),
                he1.eq(lcd_enable_uvc),
                d1.eq(lcd_db_uvc),
            ),
        ]

        # ESP32 Control (PHY_CLKOUT & gClk domains) ------------------------------------------------

        self.esp32_ctrl = esp32_ctrl = ClockDomainsRenamer("gclk")(ESP32Control(esp32, esp_uart))

        # Buttons (gClk domain) --------------------------------------------------------------------

        self.buttons = btns_phy = ClockDomainsRenamer("gclk")(Buttons(buttons))

        # Debug control: virtual buttons OR'ed with the physical ones, status registers.
        self.debug_ctrl = debug_ctrl = DebugControl()
        btns = SimpleNamespace()
        for name in BUTTONS:
            btn = Signal(name=f"btn_{name}")
            self.comb += btn.eq(getattr(btns_phy, name) | getattr(debug_ctrl, name))
            setattr(btns, name, btn)

        # Menu button: OR physical menu button with MCU menu bit, gate until cart is stable and
        # menu init is complete.
        btn_menu_ored = Signal()
        menu_gated    = Signal()
        self.comb += [
            btn_menu_ored.eq(buttons.menu & ~mcu_buttons[8] & ~debug_ctrl.menu),
            If(q_menu_init & (cart_det_sr[3:7] == 0xF),
                menu_gated.eq(btn_menu_ored),
            ).Else(
                menu_gated.eq(1),
            ),
        ]

        # HDMI Debug Signals -----------------------------------------------------------------------

        # Route internal status signals to HDMI pads for logic-analyzer probing.
        self.comb += [
            hdmi.d_p[2].eq(lcd_on_int),
            hdmi.d_n[2].eq(h_draw_osd),
            hdmi.d_p[1].eq(lcd_off_overwrite),
            hdmi.d_n[1].eq(gb_lcd_on),
            hdmi.d_p[0].eq(gb_lcd_vsync),
            hdmi.d_n[0].eq(gb_lcd_mode[1]),
            hdmi.clk_p.eq(gb_lcd_clkena),
            hdmi.clk_n.eq(h_gb_write),
        ]

        # I2S_BCLK = menuDisabled (ESP32 menu state).
        self.comb += i2s.bclk.eq(menu_disabled)

        # LCD SPI Init (pClk domain) ---------------------------------------------------------------

        self.st7785_init = st7785_init = ClockDomainsRenamer("pclk")(ST7785Init(load_st7785_sequence()))
        self.comb += [
            st7785_init.reset.eq(memrst),
            lcd.spi_csx.eq(st7785_init.lcd_cs),
            lcd.spi_sclk.eq(st7785_init.lcd_sck),
            lcd.spi_sda.eq(st7785_init.lcd_sda_sdi),
            lcd.reset.eq(st7785_init.lcd_rst),
            lcd_init_done.eq(st7785_init.lcd_init_done),
        ]

        # Video System -----------------------------------------------------------------------------

        self.video = video = VideoPipeline(lcd)
        self.comb += [
            # Game Boy LCD.
            video.gb_clkena.eq(gb_lcd_clkena),
            video.gb_data.eq(gb_lcd_data),
            video.gb_mode.eq(gb_lcd_mode),
            video.gb_on.eq(gb_lcd_on),
            video.gb_vsync.eq(gb_lcd_vsync),
            # Frame Buffer / OSD.
            h_gb_newline.eq(video.fb_new_line),
            h_gb_address.eq(video.fb_address),
            h_gb_write.eq(video.fb_write),
            h_gb_data.eq(video.fb_data),
            video.fb_prev.eq(h_wr_burst_q),
            video.osd_data.eq(h_wr_burst_q2),
            h_draw_osd.eq(video.draw_osd),
            # Controls.
            video.menu_disabled.eq(menu_disabled),
            video.lcd_init_done.eq(lcd_init_done),
            video.lcd_en.eq(lcd_en),
            video.frame_blend.eq(system_control[1]),
            video.correct_lcd.eq(system_control[2]),
            video.correct_uvc.eq(system_control[3]),
            video.voltage_low.eq(low_battery),
            video.low_batt_mode.eq(system_control[13:15]),
            video.show_timer.eq(0),
            video.run_timer.eq(system_control[9]),
            video.reset_timer.eq(system_control[10]),
            video.second.eq(ticks.second),
            video.percent.eq(ticks.percent),
            video.debug_system.eq(debug_system),
            video.debug_on.eq(0),
            # UVC.
            lcd_enable_uvc.eq(video.uvc_en),
            lcd_db_uvc.eq(video.uvc_db),
        ]

        # Audio: TLV320 Codec Control (hClk domain) + I2S (gClk domain) ----------------------------

        self.codec_ctrl = codec_ctrl = ClockDomainsRenamer("hclk")(CodecControl(
            pads         = i2c,
            sys_clk_freq = hclk_freq,
            registers    = load_tlv320_registers(),
        ))
        self.comb += [
            codec_ctrl.reset.eq(~crg.pll.locked),
            codec_ctrl.mute.eq(system_control[0]),
        ]
        h_headphones = codec_ctrl.gpio[1]

        # Audio samples: Emulation (hClk) -> I2S/USB (gClk).
        self.audio_cdc = audio_cdc = BusSynchronizer(32, "hclk", "gclk")
        g_left  = Signal(16)
        g_right = Signal(16)
        self.comb += [
            audio_cdc.i.eq(Cat(left, right)),
            Cat(g_left, g_right).eq(audio_cdc.o),
        ]

        self.codec_i2s = codec_i2s = ClockDomainsRenamer("gclk")(CodecI2S(audio))
        self.comb += [
            codec_i2s.enable.eq(crg.pll.locked),
            codec_i2s.left.eq(g_left),
            codec_i2s.right.eq(g_right),
            codec_i2s.mute.eq(system_control[0] | (codec_ctrl.volume > 0x76)),
            codec_i2s.headphones.eq(h_headphones),
        ]

        # Memory System ----------------------------------------------------------------------------

        # PSRAM Wishbone bus: CPU main RAM (BIOS demo: upper 4MB, Doom: from DOOM_RAM_OFFSET, 64-bit
        # lines) or host access over the debug bridge (whole PSRAM, 32-bit: ROM upload, cartridge
        # RAM, framebuffers).
        main_ram_offset, main_ram_size = {
            (True,  False): (0x400000,        4*MB),
            (False, True):  (DOOM_RAM_OFFSET, DOOM_RAM_SIZE),
        }.get((with_bios, with_doom), (0x000000, 8*MB))
        self.memory = memory = MemorySystem(qspi_pads=qspi, psram_pads=ps,
            with_bus       = with_cpu or with_debug_bridge,
            bus_base       = main_ram_offset,
            bus_data_width = 64 if with_cpu else 32,
            with_vcart     = with_vcart,
        )

        # Virtual Cartridge (ROM/cartridge RAM in the PSRAM, loaded from the host) -----------------

        if with_vcart:
            self.vcart     = vcart = VirtualCart(memory.vcart_port, memory.ctrl.dout)
            self.vcart_csr = VirtualCartCSR(vcart)
        self.comb += [
            memory.reset.eq(memrst),
            q_menu_init.eq(memory.menu_init),
            # Game Boy framebuffer write.
            memory.gb_new_line.eq(h_gb_newline),
            memory.gb_address.eq(h_gb_address),
            memory.gb_write.eq(h_gb_write),
            memory.gb_data.eq(h_gb_data),
            # Framebuffer/OSD line reads.
            memory.h_valid.eq(gb_lcd_clkena),
            memory.h_hsync.eq(gb_lcd_mode[1]),
            memory.h_vsync.eq(gb_lcd_vsync),
            h_wr_burst_q.eq(memory.fb_data),
            h_wr_burst_q2.eq(memory.osd_data),
        ]

        # CPU Main RAM (LiteX BIOS demo, Doom): PSRAM above the framebuffers/BIST, behind a L2 cache
        # doing 8-byte line bursts (64-bit lines: the cache data memory is split per byte lane, 1
        # BSRAM each).
        if with_cpu:
            main_ram = wishbone.Interface(data_width=32, address_width=32, addressing="word")
            self.l2_cache = wishbone.Cache(
                cachesize = 8192//4,
                master    = main_ram,
                slave     = memory.bus,
                reverse   = False,
            )
            self.add_config("L2_SIZE", 8192)
            self.bus.add_slave(name="main_ram", slave=main_ram, region=SoCRegion(
                origin = self.mem_map["main_ram"],
                size   = main_ram_size,
                mode   = "rwx",
            ))

        # PSRAM (debug bridge): whole PSRAM (8MB) at PSRAM_BASE.
        if with_debug_bridge and not with_cpu:
            self.bus.add_slave(name="psram", slave=memory.bus, region=SoCRegion(
                origin = PSRAM_BASE,
                size   = 8*MB,
                mode   = "rw",
            ))

        # Emulation System -------------------------------------------------------------------------

        if with_cpu:
            # Firmware peripherals: buttons.
            self.demo_buttons = ButtonsCSR(btns, menu=~btn_menu_ored)

            # Audio in place of the Game Boy one: tone generator (BIOS demo) or PCM samples (Doom).
            if with_bios:
                self.tone = tone = ToneGenerator(hclk_freq, cd="hclk")
                self.comb += [
                    left.eq(tone.sample),
                    right.eq(tone.sample),
                ]
            else:
                self.pcm = pcm = PCMAudio(sys_clk_freq)
                self.sync.hclk += [ # pClk -> hClk (same PLL, samples quasi-static).
                    left.eq(pcm.left),
                    right.eq(pcm.right),
                ]

            # LCD in place of the Game Boy one: terminal (BIOS demo) or CPU framebuffer (Doom).
            if with_bios:
                self.terminal = lcd_source = LCDTerminal()
            else:
                self.framebuffer = lcd_source = LCDFramebuffer()
                self.bus.add_slave(name="framebuffer", slave=lcd_source.bus, region=SoCRegion(
                    origin = 0x90000000,
                    size   = 0x10000,
                    mode   = "rw",
                    cached = False,
                ))

            # Cartridge/IR/link idle (as when the Game Boy core doesn't access them).
            for pad in [cart.d, cart.rst, link.clk]:
                self.specials += TSTriple(len(pad)).get_tristate(pad) # Not driven.
            self.comb += [
                gb_lcd_clkena.eq(lcd_source.gb_clkena),
                gb_lcd_data.eq(lcd_source.gb_data),
                gb_lcd_mode.eq(lcd_source.gb_mode),
                gb_lcd_on.eq(lcd_source.gb_on),
                gb_lcd_vsync.eq(lcd_source.gb_vsync),
                cart.a.eq(0),
                cart.clk.eq(0),
                cart.cs.eq(1),
                cart.rd.eq(1),
                cart.wr.eq(1),
                cart.data_dir_e.eq(1),
                ir.led.eq(0),
                link.out.eq(0),
            ]
        else:
            self.specials += Instance("emu_system_top",
                i_hclk              = ClockSignal("hclk"),
                i_pclk              = ClockSignal("pclk"),
                i_reset_n           = ~memrst,
                i_POWER_GOOD        = ~power.on_fpga,
                # Palette.
                i_customPaletteEna  = palette_bg_in[63],
                i_paletteOff        = system_control[12],
                i_paletteBGIn       = palette_bg_in,
                i_paletteOBJ0In     = palette_obj0_in,
                i_paletteOBJ1In     = palette_obj1_in,
                o_gbc_mode          = gbc_mode,
                o_gpd               = gpd,
                # Buttons.
                i_BTN_NODIAGONAL    = system_control[11],
                i_BTN_A             = btns.a          | mcu_buttons[3],
                i_BTN_B             = btns.b          | mcu_buttons[2],
                i_BTN_DPAD_DOWN     = btns.dpad_down  | mcu_buttons[7],
                i_BTN_DPAD_LEFT     = btns.dpad_left  | mcu_buttons[6],
                i_BTN_DPAD_RIGHT    = btns.dpad_right | mcu_buttons[5],
                i_BTN_DPAD_UP       = btns.dpad_up    | mcu_buttons[4],
                i_BTN_MENU          = ~btn_menu_ored,
                i_BTN_SEL           = btns.sel        | mcu_buttons[1],
                i_BTN_START         = btns.start      | mcu_buttons[0],
                i_MENU_CLOSED       = menu_disabled & ~slide_out_active,
                # Cartridge.
                o_CART_A            = cart.a,
                o_CART_CLK          = cart.clk,
                o_CART_CS           = cart.cs,
                io_CART_D           = cart.d,
                o_CART_RD           = cart.rd,
                io_CART_RST         = cart.rst,
                o_CART_WR           = cart.wr,
                o_CART_DATA_DIR_E   = cart.data_dir_e,
                # IR.
                i_IR_RX             = ir.rx,
                o_IR_LED            = ir.led,
                # Link Cable.
                io_LINK_CLK         = link.clk,
                i_LINK_IN           = getattr(link, "in"),
                o_LINK_OUT          = link.out,
                # LCD Status.
                o_lcd_on_int        = lcd_on_int,
                o_lcd_off_overwrite = lcd_off_overwrite,
                o_boot_rom_enabled  = boot_rom_enabled,
                # Audio.
                o_left              = left,
                o_right             = right,
                # Game Boy LCD.
                i_LCD_INIT_DONE     = lcd_init_done,
                o_gb_lcd_clkena     = gb_lcd_clkena,
                o_gb_lcd_mode       = gb_lcd_mode,
                o_gb_lcd_on         = gb_lcd_on,
                o_gb_lcd_vsync      = gb_lcd_vsync,
                o_gb_lcd_data       = gb_lcd_data,
                # Virtual Cartridge.
                **(dict(
                    i_VCART_EN      = vcart.enable,
                    i_VCART_HOLD    = self.vcart_csr.hold,
                    i_VCART_WAIT    = vcart.wait,
                    i_VCART_DATA    = vcart.data,
                    o_VCART_A       = vcart.a,
                    o_VCART_RD      = vcart.rd,
                    o_VCART_WR      = vcart.wr,
                    o_VCART_DOUT    = vcart.din,
                    o_VCART_DMA     = vcart.dma,
                    o_VCART_RESET   = vcart.reset,
                ) if with_vcart else dict(
                    i_VCART_EN      = 0,
                    i_VCART_HOLD    = 0,
                    i_VCART_WAIT    = 0,
                    i_VCART_DATA    = 0,
                )),
            )

        # Link Port: LINK_SD not driven by emu_system_top.
        self.comb += link.sd.eq(0)

        # USB CDC UART: ESP32 passthrough (default), LiteX UARTBone debug bridge (+ crossover UART
        # console for Doom) or BIOS console.
        usb_uart = Record([("tx", 1), ("rx", 1), ("dtr", 1), ("rts", 1)])
        if with_bios:
            self.comb += [
                esp32_ctrl.usb_rxd.eq(1),
                esp32_ctrl.usb_dtr.eq(0),
                esp32_ctrl.usb_rts.eq(0),
            ]
            self.add_uart(uart_pads=usb_uart, baudrate=debug_bridge_baudrate)
            # Console also on the LCD terminal (bytes sent by the UART PHY).
            self.comb += [
                self.terminal.sink.valid.eq(self.uart_phy.sink.valid & self.uart_phy.sink.ready),
                self.terminal.sink.data.eq(self.uart_phy.sink.data),
            ]
        elif with_debug_bridge or with_doom:
            # Keep the ESP32 running normally (EN high, IO0 high) with an idle UART.
            self.comb += [
                esp32_ctrl.usb_rxd.eq(1),
                esp32_ctrl.usb_dtr.eq(0),
                esp32_ctrl.usb_rts.eq(0),
            ]
            # UARTBone on the CDC byte stream (USB rate, no UART: the host baudrate is ignored).
            class CDCStreamPHY:
                pass
            cdc_phy = CDCStreamPHY()
            self.cdc_rx = stream.ClockDomainCrossing([("data", 8)], cd_from="phy", cd_to="sys")
            self.cdc_tx = stream.ClockDomainCrossing([("data", 8)], cd_from="sys", cd_to="phy")
            cdc_phy.source = self.cdc_rx.source
            cdc_phy.sink   = self.cdc_tx.sink
            self.uartbone = UARTBone(
                phy           = cdc_phy,
                clk_freq      = sys_clk_freq,
                address_width = self.bus.address_width,
            )
            self.bus.add_master(name="uartbone", master=self.uartbone.wishbone)
            if with_doom:
                self.add_uart(uart_name="crossover")
        else:
            self.comb += [
                esp32_ctrl.usb_rxd.eq(usb_uart.rx),
                usb_uart.tx.eq(esp32_ctrl.usb_txd),
                esp32_ctrl.usb_dtr.eq(usb_uart.dtr),
                esp32_ctrl.usb_rts.eq(usb_uart.rts),
            ]

        # USB UVC+UAC+UART System ------------------------------------------------------------------

        self.usb = usb_dev = USBDevice(platform, clk_24, usb,
            with_utmi_monitor = with_debug_bridge and with_utmi_monitor,
            with_cdc_stream   = with_debug_bridge or with_doom,
            **({} if uvc_frames is None else {"uvc_frames": uvc_frames}))
        if with_debug_bridge or with_doom:
            self.comb += [
                usb_dev.cdc_source.connect(self.cdc_rx.sink),
                self.cdc_tx.source.connect(usb_dev.cdc_sink),
            ]
        self.comb += [
            usb_dev.reset.eq(usb_rst),
            esp32_ctrl.usb_locked.eq(usb_dev.locked),
            usb_dev.player_num.eq(Cat(system_control[4:8], Constant(0, 4))),
            # UART.
            usb_uart.rx.eq(usb_dev.uart_txd),
            usb_dev.uart_rxd.eq(usb_uart.tx),
            usb_uart.dtr.eq(usb_dev.uart_dtr),
            usb_uart.rts.eq(usb_dev.uart_rts),
            # Audio.
            usb_dev.left.eq(g_left),
            usb_dev.right.eq(g_right),
            # UVC Video.
            usb_dev.line_valid.eq(hr1),
            usb_dev.enable.eq(he1),
            usb_dev.frame_valid.eq(vr1),
            usb_dev.video.eq(d1),
        ]

        # Battery ADC (gClk domain) ----------------------------------------------------------------

        self.battery_adc = battery_adc = ClockDomainsRenamer("gclk")(BatteryADC(vbat_adc))
        self.comb += battery_adc.enable.eq(crg.pll.locked)

        # System Monitor (gClk domain) -------------------------------------------------------------

        sm_num_channels = 10

        # UART (FPGA <-> ESP32 MCU).
        self.sm_uart = sm_uart = ClockDomainsRenamer("gclk")(SystemMonitorUART(serial, clk_freq=gclk_freq))
        self.comb += sm_uart.enable.eq(crg.pll.locked)

        # Packet transport (RX decode, channel arbiter, TX framing).
        self.sm_bridge = sm_bridge = ClockDomainsRenamer("gclk")(SystemMonitorBridge(num_channels=sm_num_channels))
        self.comb += [
            sm_bridge.reset.eq(~crg.pll.locked),
            sm_bridge.menu_disabled.eq(menu_disabled),
            sm_bridge.uart_tx_busy.eq(sm_uart.tx_busy),
            sm_bridge.uart_rx_data.eq(sm_uart.rx_data),
            sm_bridge.uart_rx_val.eq(sm_uart.rx_val),
            sm_uart.tx_data.eq(sm_bridge.uart_tx_data),
            sm_uart.tx_val.eq(sm_bridge.uart_tx_val),
        ]

        # Payloads.
        self.sm_payloads = sm_payloads = SystemMonitorPayloads(num_channels=sm_num_channels)
        self.comb += [
            sm_payloads.menu_disabled.eq(menu_disabled),
            sm_payloads.btn_a.eq(btns.a),
            sm_payloads.btn_b.eq(btns.b),
            sm_payloads.btn_down.eq(btns.dpad_down),
            sm_payloads.btn_left.eq(btns.dpad_left),
            sm_payloads.btn_right.eq(btns.dpad_right),
            sm_payloads.btn_up.eq(btns.dpad_up),
            sm_payloads.btn_menu.eq(menu_gated),
            sm_payloads.btn_sel.eq(btns.sel),
            sm_payloads.btn_start.eq(btns.start),
            sm_payloads.h_headphones.eq(h_headphones),
            sm_payloads.h_volume.eq(codec_ctrl.volume[:7]),
            sm_payloads.pmic_sys_status.eq(codec_ctrl.pmic_sys_status),
            sm_payloads.system_control.eq(system_control),
            sm_payloads.gbc_mode.eq(gbc_mode),
            sm_payloads.gpd.eq(gpd),
            sm_payloads.tx_channel.eq(sm_bridge.tx_channel),
            sm_payloads.tx_bytepos.eq(sm_bridge.tx_bytepos),
            sm_bridge.channels_new_data_valid.eq(sm_payloads.channels_new_data_valid),
            sm_bridge.tx_byte_count.eq(sm_payloads.tx_byte_count),
            sm_bridge.tx_senddata.eq(sm_payloads.tx_senddata),
        ]

        # Menu / UI / Battery / Palette.
        self.sm_ctrl = sm_ctrl = ClockDomainsRenamer("gclk")(SystemMonitorControl(num_channels=sm_num_channels))
        self.comb += [
            sm_ctrl.reset.eq(~crg.pll.locked),
            # Buttons.
            sm_ctrl.btn_a.eq(btns.a),
            sm_ctrl.btn_b.eq(btns.b),
            sm_ctrl.btn_down.eq(btns.dpad_down),
            sm_ctrl.btn_left.eq(btns.dpad_left),
            sm_ctrl.btn_right.eq(btns.dpad_right),
            sm_ctrl.btn_up.eq(btns.dpad_up),
            sm_ctrl.btn_menu.eq(menu_gated),
            sm_ctrl.btn_sel.eq(btns.sel),
            sm_ctrl.btn_start.eq(btns.start),
            # LCD.
            menu_disabled.eq(sm_ctrl.menu_disabled),
            lcd_backlight_init.eq(sm_ctrl.lcd_backlight_init),
            sm_ctrl.lcd_init_done.eq(lcd_init_done & ~boot_rom_enabled),
            lcd.pwm.eq(sm_ctrl.lcd_pwm),
            # ADC.
            battery_adc.req.eq(sm_ctrl.adc_req),
            sm_ctrl.adc_ready.eq(battery_adc.ready),
            sm_ctrl.adc_value.eq(battery_adc.value),
            audio.adc_sel.eq(sm_ctrl.adc_sel),
            # System Status.
            mcu_buttons.eq(sm_ctrl.mcu_buttons),
            sm_ctrl.pmic_sys_status.eq(codec_ctrl.pmic_sys_status),
            sm_ctrl.second.eq(ticks.second),
            sm_ctrl.half_second.eq(ticks.half_second),
            debug_system.eq(sm_ctrl.debug_system),
            low_battery.eq(sm_ctrl.low_battery),
            # LED Control.
            status_led.green.eq(sm_ctrl.led_green),
            status_led.red.eq(sm_ctrl.led_red),
            status_led.yellow.eq(sm_ctrl.led_yellow),
            status_led.white.eq(sm_ctrl.led_white),
            # System Control / Palette.
            system_control.eq(sm_ctrl.system_control),
            palette_bg_in.eq(sm_ctrl.palette_bg),
            palette_obj0_in.eq(sm_ctrl.palette_obj0),
            palette_obj1_in.eq(sm_ctrl.palette_obj1),
            # Decoded monitor transport.
            sm_ctrl.rx_address.eq(sm_bridge.rx_address),
            sm_ctrl.rx_data.eq(sm_bridge.rx_data),
            sm_ctrl.rx_data_val.eq(sm_bridge.rx_data_val),
            sm_ctrl.tx_channel.eq(sm_bridge.tx_channel),
            sm_ctrl.write_done.eq(sm_bridge.write_done),
            # Payload requests/values.
            sm_payloads.request_buttons.eq(sm_ctrl.request_buttons),
            sm_payloads.request_version.eq(sm_ctrl.request_version),
            sm_payloads.update_brightness.eq(sm_ctrl.update_brightness),
            sm_payloads.request_system_status_extended.eq(sm_ctrl.request_system_status_extended),
            sm_payloads.request_gpd.eq(sm_ctrl.request_gpd),
            sm_payloads.volt.eq(sm_ctrl.volt),
            sm_payloads.bat_is_li.eq(sm_ctrl.bat_is_li),
            sm_payloads.transmit_volt.eq(sm_ctrl.transmit_volt),
            sm_payloads.brightness.eq(sm_ctrl.brightness),
            sm_payloads.lowpower_backlight.eq(sm_ctrl.lowpower_backlight),
        ]

        # Debug Control Status ---------------------------------------------------------------------

        self.comb += [
            debug_ctrl.bist_done.eq(memory.bist_done),
            debug_ctrl.bist_failed.eq(memory.bist_failed),
            debug_ctrl.lcd_init_done.eq(lcd_init_done),
            debug_ctrl.menu_disabled.eq(menu_disabled),
            debug_ctrl.low_battery.eq(low_battery),
            debug_ctrl.system_control.eq(system_control),
            debug_ctrl.volt.eq(sm_payloads.volt),
            debug_ctrl.adc_value.eq(battery_adc.value),
            debug_ctrl.bat_is_li.eq(sm_payloads.bat_is_li),
            debug_ctrl.volume.eq(codec_ctrl.volume),
            debug_ctrl.headphones.eq(h_headphones),
            debug_ctrl.pmic_sys_status.eq(codec_ctrl.pmic_sys_status),
            debug_ctrl.uvc_hbw.eq(usb_dev.uvc.hbw),
            debug_ctrl.uvc_frame_index.eq(usb_dev.uvc.frame_index),
            debug_ctrl.uvc_hbw_count.eq(usb_dev.uvc.hbw_count),
            debug_ctrl.uvc_frame_count.eq(usb_dev.uvc.frame_count),
            debug_ctrl.uvc_debug.eq(Cat(usb_dev.uvc.max_level, Constant(0, 3), usb_dev.uvc.drop_count,
                usb_dev.uvc.skip_count, usb_dev.uvc.start_count)),
        ]

# Build --------------------------------------------------------------------------------------------

def compile_firmware_libraries(builder, names=("libc", "libcompiler_rt", "libbase")):
    """Firmware libraries for a CPU without BIOS/ROM (Doom: LiteX only compiles them for a BIOS)."""
    for name, src_dir in builder.software_packages:
        if name in names:
            dst_dir = os.path.join(builder.software_dir, name)
            os.makedirs(dst_dir, exist_ok=True)
            subprocess.check_call(["make", f"-j{os.cpu_count()}", "-C", dst_dir, "-f",
                os.path.join(src_dir, "Makefile")])

def main():
    parser = argparse.ArgumentParser(description="ChromatiX: LiteX based FPGA design for the ModRetro Chromatic.")

    # Build/Load/Flash.
    parser.add_argument("--build",      action="store_true", help="Build bitstream.")
    parser.add_argument("--no-compile", action="store_true", help="Generate build files without running the toolchain.")
    parser.add_argument("--load",       action="store_true", help="Load bitstream (to SRAM, USB will not enumerate).")
    parser.add_argument("--flash",      action="store_true", help="Flash bitstream (to SPI Flash) and reboot.")

    # Toolchain.
    parser.add_argument("--toolchain",  default="gowin",                    help="FPGA toolchain (gowin).")
    parser.add_argument("--gowin-path", default=os.environ.get("GOWIN_PATH"), help="Gowin IDE install directory (or GOWIN_PATH env variable, ex: ~/tools/gowin_1.9.12.04/IDE).")

    # SoC.
    parser.add_argument("--with-debug-bridge",     action="store_true",       help="Replace the USB CDC <-> ESP32 UART passthrough with a LiteX UARTBone debug bridge.")
    parser.add_argument("--debug-bridge-baudrate", default=115200, type=int,  help="Debug bridge baudrate.")
    parser.add_argument("--uvc-sizes",             default="320x288,160x144", help="UVC frame sizes (1st: default), ex: 160x144 or 320x288,160x144.")
    parser.add_argument("--with-bios",             action="store_true",       help="LiteX BIOS demo: VexRiscv SoC in place of the Game Boy core, console on USB CDC and LCD/UVC.")
    parser.add_argument("--with-doom",             action="store_true",       help="Doom: VexRiscv SoC in place of the Game Boy core, CPU framebuffer/PCM audio, firmware loaded over USB (UARTBone).")
    parser.add_argument("--with-utmi-monitor",     action="store_true",       help="USB UTMI packet recorder (debug bridge).")
    args = parser.parse_args()

    # Platform.
    platform = Platform(toolchain=args.toolchain)

    # Gowin IDE selection (LiteX sets the bundled libs for gw_sh only).
    if args.gowin_path is not None:
        gowin_path = os.path.expanduser(args.gowin_path)
        os.environ["PATH"]            = os.path.join(gowin_path, "bin") + os.pathsep + os.environ["PATH"]
        os.environ["QT_QPA_PLATFORM"] = "offscreen"
    if not (args.with_bios or args.with_doom):
        add_verilog_sources(platform) # Game Boy core.
    add_timing_constraints(platform)

    # SoC.
    soc = BaseSoC(platform,
        with_debug_bridge     = args.with_debug_bridge,
        with_bios             = args.with_bios,
        with_doom             = args.with_doom,
        with_utmi_monitor     = args.with_utmi_monitor,
        debug_bridge_baudrate = args.debug_bridge_baudrate,
        uvc_frames            = [tuple(int(v) for v in size.split("x")) for size in args.uvc_sizes.split(",")],
    )

    # Build.
    builder = Builder(soc,
        output_dir = "build",
        csr_csv    = "scripts/csr.csv",
        bios_lto   = True, # BIOS fits the 24KB integrated ROM.
        libc_mode  = "full" if args.with_doom else "minimal", # Doom: full picolibc (stdio, malloc...).
    )
    if args.build:
        builder.build(build_name="chromatic", run=not args.no_compile)
        if args.with_doom:
            compile_firmware_libraries(builder)

    # Load / Flash.
    bitstream = os.path.join(builder.gateware_dir, "chromatic.fs")
    if args.load:
        prog = platform.create_programmer()
        prog.load_bitstream(bitstream)
    if args.flash:
        prog = platform.create_programmer()
        prog.flash(0, bitstream, reset=True)

if __name__ == "__main__":
    main()
