#!/usr/bin/env python3

#
# This file is part of ChromatiX.
#
# Copyright (c) 2026 Florent Kermarrec <florent@enjoy-digital.fr>
# SPDX-License-Identifier: BSD-2-Clause

"""SDR firmware tables (tables.h): FFT twiddles, Hann window, 4x6 font (from the LCD terminal)."""

import os
import sys
import math

sys.path.insert(0, os.path.join(os.path.dirname(os.path.abspath(__file__)), "..", ".."))
from chromatix.gateware.terminal import FONT_4X6

FFT_SIZE = 512

def c_array(ctype, name, values, per_line=12):
    lines = [f"static const {ctype} {name}[{len(values)}] = {{"]
    for i in range(0, len(values), per_line):
        lines.append("\t" + ", ".join(str(v) for v in values[i:i + per_line]) + ",")
    lines.append("};")
    return "\n".join(lines)

def main():
    twiddle_cos = [round(32767*math.cos(2*math.pi*k/FFT_SIZE)) for k in range(FFT_SIZE//2)]
    twiddle_sin = [round(32767*math.sin(2*math.pi*k/FFT_SIZE)) for k in range(FFT_SIZE//2)]
    hann        = [round(32767*0.5*(1 - math.cos(2*math.pi*n/FFT_SIZE))) for n in range(FFT_SIZE)]
    font        = [sum(row << (3*(5 - r)) for r, row in enumerate(glyph)) for glyph in FONT_4X6]
    out = [
        "// Generated by gen_tables.py: don't edit.",
        "",
        "#ifndef TABLES_H",
        "#define TABLES_H",
        "",
        "#include <stdint.h>",
        "",
        f"#define FFT_SIZE {FFT_SIZE}",
        "",
        "/* FFT twiddles (Q15): cos/sin(2*pi*k/FFT_SIZE), k < FFT_SIZE/2. */",
        c_array("int16_t", "twiddle_cos", twiddle_cos),
        c_array("int16_t", "twiddle_sin", twiddle_sin),
        "",
        "/* Hann window (Q15). */",
        c_array("int16_t", "hann", hann),
        "",
        "/* 4x6 font (\"Tom Thumb\", Robey Pointer, MIT license), ASCII 0x20-0x7e: 6 rows of 3 pixels,",
        "   row 0 in bits 17:15, MSB left. */",
        c_array("uint32_t", "font4x6", font, per_line=8),
        "",
        "#endif",
        "",
    ]
    path = os.path.join(os.path.dirname(os.path.abspath(__file__)), "tables.h")
    with open(path, "w", encoding="utf-8") as f:
        f.write("\n".join(out))

if __name__ == "__main__":
    main()
